swagger: "2.0"
info:
  version: "1.0.0"
  title: Words counter web api
basePath: /
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/octet-stream
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /word-statistics:
    x-swagger-router-controller: words
    get:
      description: get how many times the word appeared till now in former texts.
      operationId: getWordStatistics
      parameters:
        - name: word
          in: query
          description: the word to count statistics
          required: true
          type: string
      tags:
        - words
      responses:
        200:
          description: how many time this word appeared
        default:
          description: Unexpected error
  /word-counter:
    x-swagger-router-controller: words
    post:
      description: count words in the text passed in the body.
      operationId: countWordsFromText
      tags:
        - words
      parameters:
        - in: body
          name: source
          description: Source should be "body"/"filepath"/"url". Fill text/filepath/url accordingly.
          schema:
            required:
              - source
            properties:
              source:
                description: the text to parse and count words from- body/filepath/url.
                type: string
                enum: ["body", "filepath", "url"]
              text:
                description: the text to count words from (if source is body).
                type: string
              filepath:
                description: the filepath of the text to count words from.
                type: string
              url:
                description: the url of the text to count words from.
                type: string
      responses:
        201:
          description: words from the text were countered.
